import type { TestCase } from './types'

export type ChallengeTier = 'novice' | 'apprentice' | 'journeyman'

export interface Challenge {
  slug: string
  title: string
  tier: ChallengeTier
  tags: string[]
  /** One-paragraph statement of the task. */
  prompt: string
  /** Worked examples shown beneath the prompt. */
  examples?: string[]
  starter: string
  solution: string
  tests: TestCase[]
  hints: string[]
}

export const TIER_LABEL: Record<ChallengeTier, string> = { novice: 'Novice', apprentice: 'Apprentice', journeyman: 'Journeyman' }
export const TIER_COLOR: Record<ChallengeTier, string> = { novice: '#22c55e', apprentice: '#f59e0b', journeyman: '#ef4444' }

/** The Python challenge ladder. Every check runs in the browser against the learner's namespace. */
export const challenges: Challenge[] = [
  // ─────────────────────────────── Novice ───────────────────────────────
  {
    slug: 'sum-of-digits',
    title: 'Sum of digits',
    tier: 'novice',
    tags: ['numbers', 'loops'],
    prompt: 'Write digit_sum(n) that returns the sum of the decimal digits of a non-negative integer.',
    examples: ['digit_sum(1234) → 10', 'digit_sum(0) → 0'],
    starter: `def digit_sum(n):\n    ...\n\n\nprint(digit_sum(1234))\n`,
    solution: `def digit_sum(n):\n    return sum(int(d) for d in str(n))\n\n\nprint(digit_sum(1234))\n`,
    hints: ['str(n) turns the number into characters you can loop over.', 'Or use arithmetic: n % 10 is the last digit and n // 10 drops it.'],
    tests: [
      { name: 'digit_sum(1234) is 10', check: `assert digit_sum(1234) == 10` },
      { name: 'digit_sum(0) is 0', check: `assert digit_sum(0) == 0` },
      { name: 'Large number', check: `assert digit_sum(99999999999) == 99` },
    ],
  },
  {
    slug: 'reverse-words',
    title: 'Reverse the words',
    tier: 'novice',
    tags: ['strings'],
    prompt: 'Write reverse_words(sentence) that returns the sentence with the order of the words reversed. Words are separated by single spaces; keep each word intact.',
    examples: ['reverse_words("the quick brown fox") → "fox brown quick the"'],
    starter: `def reverse_words(sentence):\n    ...\n\n\nprint(reverse_words("the quick brown fox"))\n`,
    solution: `def reverse_words(sentence):\n    return " ".join(reversed(sentence.split()))\n\n\nprint(reverse_words("the quick brown fox"))\n`,
    hints: ['sentence.split() gives a list of words.', '" ".join(list_of_words) glues them back together. reversed() or [::-1] flips the list.'],
    tests: [
      { name: 'Four words', check: `assert reverse_words("the quick brown fox") == "fox brown quick the"` },
      { name: 'Single word unchanged', check: `assert reverse_words("hello") == "hello"` },
      { name: 'Words stay intact', check: `assert reverse_words("Ada Lovelace") == "Lovelace Ada"` },
    ],
  },
  {
    slug: 'count-vowels',
    title: 'Count the vowels',
    tier: 'novice',
    tags: ['strings', 'loops'],
    prompt: 'Write count_vowels(text) that returns how many vowels (a, e, i, o, u — either case) the text contains.',
    examples: ['count_vowels("ScholastiCoder") → 5'],
    starter: `def count_vowels(text):\n    ...\n\n\nprint(count_vowels("ScholastiCoder"))\n`,
    solution: `def count_vowels(text):\n    return sum(1 for ch in text.lower() if ch in "aeiou")\n\n\nprint(count_vowels("ScholastiCoder"))\n`,
    hints: ['Lower-case the text first so you only have to check five letters.', 'ch in "aeiou" is True for a vowel.'],
    tests: [
      { name: 'ScholastiCoder has 5 vowels', check: `assert count_vowels("ScholastiCoder") == 5` },
      { name: 'Mixed case', check: `assert count_vowels("AEIOU aeiou") == 10` },
      { name: 'No vowels', check: `assert count_vowels("rhythm") == 0` },
    ],
  },
  {
    slug: 'largest-without-max',
    title: 'Largest, by hand',
    tier: 'novice',
    tags: ['lists', 'loops'],
    prompt: 'Write largest(numbers) that returns the biggest number in a non-empty list — without using the built-in max() or sorted().',
    examples: ['largest([3, 9, 2, 7]) → 9'],
    starter: `def largest(numbers):\n    ...\n\n\nprint(largest([3, 9, 2, 7]))\n`,
    solution: `def largest(numbers):\n    best = numbers[0]\n    for n in numbers[1:]:\n        if n > best:\n            best = n\n    return best\n\n\nprint(largest([3, 9, 2, 7]))\n`,
    hints: ['Start with the first element as the best so far.', 'Replace it whenever you see something bigger.'],
    tests: [
      { name: 'Finds 9', check: `assert largest([3, 9, 2, 7]) == 9` },
      { name: 'Negative numbers', check: `assert largest([-5, -1, -9]) == -1` },
      { name: 'No max() or sorted()', check: `assert "max(" not in _src and "sorted(" not in _src and ".sort(" not in _src` },
    ],
  },
  {
    slug: 'temperature-table',
    title: 'Temperature table',
    tier: 'novice',
    tags: ['loops', 'formatting'],
    prompt: 'Print a conversion table from 0 °C to 100 °C in steps of 20. Each line should look like 20C = 68.0F — Celsius, then Fahrenheit with one decimal place.',
    examples: ['0C = 32.0F', '20C = 68.0F', '…', '100C = 212.0F'],
    starter: `for c in range(0, 101, 20):\n    # fahrenheit = c * 9 / 5 + 32\n    pass\n`,
    solution: `for c in range(0, 101, 20):\n    f = c * 9 / 5 + 32\n    print(f"{c}C = {f:.1f}F")\n`,
    hints: ['range(0, 101, 20) gives 0, 20, …, 100.', 'f"{f:.1f}" formats to one decimal place.'],
    tests: [
      { name: 'Six lines', check: `assert len(_out.strip().splitlines()) == 6, _out` },
      { name: 'Correct conversions', check: `expected = [f"{c}C = {c * 9 / 5 + 32:.1f}F" for c in range(0, 101, 20)]\nassert _out.strip().splitlines() == expected, _out` },
    ],
  },
  {
    slug: 'factorial',
    title: 'Factorial',
    tier: 'novice',
    tags: ['numbers', 'recursion'],
    prompt: 'Write factorial(n) that returns n! — the product of every integer from 1 to n. factorial(0) is 1. Solve it with a loop or with recursion, your choice.',
    examples: ['factorial(5) → 120'],
    starter: `def factorial(n):\n    ...\n\n\nprint(factorial(5))\n`,
    solution: `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\n\nprint(factorial(5))\n`,
    hints: ['Base case: factorial(0) and factorial(1) are both 1.', 'Recursive case: n * factorial(n - 1).'],
    tests: [
      { name: 'factorial(5) is 120', check: `assert factorial(5) == 120` },
      { name: 'factorial(0) is 1', check: `assert factorial(0) == 1` },
      { name: 'factorial(20)', check: `assert factorial(20) == 2432902008176640000` },
    ],
  },
  {
    slug: 'is-leap-year',
    title: 'Leap years',
    tier: 'novice',
    tags: ['conditionals'],
    prompt: 'Write is_leap(year). A year is a leap year if it is divisible by 4, except centuries, which are leap years only when divisible by 400. So 2000 and 2024 are leap years; 1900 and 2023 are not.',
    starter: `def is_leap(year):\n    ...\n\n\nfor y in [1900, 2000, 2023, 2024]:\n    print(y, is_leap(y))\n`,
    solution: `def is_leap(year):\n    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)\n\n\nfor y in [1900, 2000, 2023, 2024]:\n    print(y, is_leap(y))\n`,
    hints: ['Check divisibility with %.', 'Combine conditions with and / or, and use parentheses to group them.'],
    tests: [
      { name: '2024 and 2000 are leap years', check: `assert is_leap(2024) is True and is_leap(2000) is True` },
      { name: '1900 and 2023 are not', check: `assert is_leap(1900) is False and is_leap(2023) is False` },
      { name: 'Returns a bool', check: `assert isinstance(is_leap(2024), bool)` },
    ],
  },
  {
    slug: 'palindrome-number',
    title: 'Palindromic numbers',
    tier: 'novice',
    tags: ['numbers', 'strings'],
    prompt: 'Write is_palindrome_number(n) that returns True if the integer reads the same backwards. Negative numbers are never palindromes.',
    examples: ['is_palindrome_number(12321) → True', 'is_palindrome_number(-121) → False'],
    starter: `def is_palindrome_number(n):\n    ...\n\n\nprint(is_palindrome_number(12321))\n`,
    solution: `def is_palindrome_number(n):\n    if n < 0:\n        return False\n    s = str(n)\n    return s == s[::-1]\n\n\nprint(is_palindrome_number(12321))\n`,
    hints: ['Handle the negative case first.', 'Convert to a string and compare with its reverse.'],
    tests: [
      { name: '12321 is a palindrome', check: `assert is_palindrome_number(12321) is True` },
      { name: '123 is not', check: `assert is_palindrome_number(123) is False` },
      { name: 'Negatives are not', check: `assert is_palindrome_number(-121) is False` },
      { name: 'Single digit', check: `assert is_palindrome_number(7) is True` },
    ],
  },

  // ───────────────────────────── Apprentice ─────────────────────────────
  {
    slug: 'caesar-cipher',
    title: 'Caesar cipher',
    tier: 'apprentice',
    tags: ['strings', 'ord/chr'],
    prompt: 'Write caesar(text, shift) that shifts every letter by shift positions in the alphabet, wrapping around from z to a. Preserve case; leave spaces, digits and punctuation untouched.',
    examples: ['caesar("Hello, World!", 3) → "Khoor, Zruog!"', 'caesar("Khoor", -3) → "Hello"'],
    starter: `def caesar(text, shift):\n    ...\n\n\nprint(caesar("Hello, World!", 3))\n`,
    solution: `def caesar(text, shift):\n    result = []\n    for ch in text:\n        if ch.isalpha():\n            base = ord("A") if ch.isupper() else ord("a")\n            result.append(chr((ord(ch) - base + shift) % 26 + base))\n        else:\n            result.append(ch)\n    return "".join(result)\n\n\nprint(caesar("Hello, World!", 3))\n`,
    hints: ['ord("a") is 97; chr(97) is "a".', 'Subtract the base, add the shift, take % 26, add the base back.', 'Build a list of characters and "".join() it at the end.'],
    tests: [
      { name: 'Shift by 3', check: `assert caesar("Hello, World!", 3) == "Khoor, Zruog!"` },
      { name: 'Negative shift decodes', check: `assert caesar("Khoor, Zruog!", -3) == "Hello, World!"` },
      { name: 'Wraps around z', check: `assert caesar("xyz XYZ", 3) == "abc ABC"` },
      { name: 'Shift of 26 is identity', check: `assert caesar("Python 3.13", 26) == "Python 3.13"` },
    ],
  },
  {
    slug: 'anagrams',
    title: 'Anagram check',
    tier: 'apprentice',
    tags: ['strings', 'sorting'],
    prompt: 'Write are_anagrams(a, b) that returns True when the two strings use exactly the same letters, ignoring case and spaces.',
    examples: ['are_anagrams("Listen", "Silent") → True', 'are_anagrams("Dormitory", "dirty room") → True'],
    starter: `def are_anagrams(a, b):\n    ...\n\n\nprint(are_anagrams("Listen", "Silent"))\n`,
    solution: `def are_anagrams(a, b):\n    norm = lambda s: sorted(s.replace(" ", "").lower())\n    return norm(a) == norm(b)\n\n\nprint(are_anagrams("Listen", "Silent"))\n`,
    hints: ['Normalise both strings the same way: lower-case, remove spaces.', 'Two strings are anagrams if their sorted letters are equal.'],
    tests: [
      { name: 'Listen / Silent', check: `assert are_anagrams("Listen", "Silent") is True` },
      { name: 'Ignores spaces', check: `assert are_anagrams("Dormitory", "dirty room") is True` },
      { name: 'Different letters', check: `assert are_anagrams("hello", "world") is False` },
      { name: 'Different counts', check: `assert are_anagrams("aab", "abb") is False` },
    ],
  },
  {
    slug: 'word-frequency-top',
    title: 'Most common words',
    tier: 'apprentice',
    tags: ['dicts', 'sorting'],
    prompt: 'Write top_words(text, n) that returns the n most frequent words as a list of (word, count) tuples, most frequent first. Compare words case-insensitively and strip punctuation. Break ties alphabetically.',
    examples: ['top_words("the cat and the hat and the bat", 2) → [("the", 3), ("and", 2)]'],
    starter: `import string\n\n\ndef top_words(text, n):\n    ...\n\n\nprint(top_words("the cat and the hat and the bat", 2))\n`,
    solution: `import string\n\n\ndef top_words(text, n):\n    counts = {}\n    for raw in text.lower().split():\n        word = raw.strip(string.punctuation)\n        if word:\n            counts[word] = counts.get(word, 0) + 1\n    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))\n    return ranked[:n]\n\n\nprint(top_words("the cat and the hat and the bat", 2))\n`,
    hints: ['word.strip(string.punctuation) removes leading/trailing punctuation.', 'Sort by (-count, word) so higher counts come first and ties are alphabetical.', 'collections.Counter has a most_common() method, but ties need your own sort.'],
    tests: [
      { name: 'Top two', check: `assert top_words("the cat and the hat and the bat", 2) == [("the", 3), ("and", 2)]` },
      { name: 'Case and punctuation', check: `assert top_words("Go! go, GO. stop", 1) == [("go", 3)]` },
      { name: 'Ties are alphabetical', check: `assert top_words("b a c", 3) == [("a", 1), ("b", 1), ("c", 1)]` },
    ],
  },
  {
    slug: 'prime-sieve',
    title: 'Sieve of Eratosthenes',
    tier: 'apprentice',
    tags: ['algorithms', 'numbers'],
    prompt: 'Write primes_up_to(limit) that returns a list of all prime numbers ≤ limit, using the sieve: mark multiples of each prime as composite rather than testing each number individually.',
    examples: ['primes_up_to(20) → [2, 3, 5, 7, 11, 13, 17, 19]'],
    starter: `def primes_up_to(limit):\n    ...\n\n\nprint(primes_up_to(20))\n`,
    solution: `def primes_up_to(limit):\n    if limit < 2:\n        return []\n    is_prime = [True] * (limit + 1)\n    is_prime[0] = is_prime[1] = False\n    for p in range(2, int(limit ** 0.5) + 1):\n        if is_prime[p]:\n            for multiple in range(p * p, limit + 1, p):\n                is_prime[multiple] = False\n    return [n for n, flag in enumerate(is_prime) if flag]\n\n\nprint(primes_up_to(20))\n`,
    hints: ['Start with a list of True flags, one per number.', 'For each p that is still True, mark p*p, p*p+p, … as False.', 'You only need to sieve up to the square root of limit.'],
    tests: [
      { name: 'Primes up to 20', check: `assert primes_up_to(20) == [2, 3, 5, 7, 11, 13, 17, 19]` },
      { name: 'Edge cases', check: `assert primes_up_to(1) == [] and primes_up_to(2) == [2]` },
      { name: '10,000 quickly', check: `import time\nt = time.perf_counter()\nassert len(primes_up_to(100000)) == 9592\nassert time.perf_counter() - t < 2, "too slow — is it really a sieve?"` },
    ],
  },
  {
    slug: 'two-sum',
    title: 'Two sum',
    tier: 'apprentice',
    tags: ['dicts', 'algorithms'],
    prompt: 'Write two_sum(numbers, target) that returns the indices of the two numbers that add up to target, as a tuple (i, j) with i < j. Assume exactly one answer exists. Aim for a single pass using a dictionary.',
    examples: ['two_sum([2, 7, 11, 15], 9) → (0, 1)'],
    starter: `def two_sum(numbers, target):\n    ...\n\n\nprint(two_sum([2, 7, 11, 15], 9))\n`,
    solution: `def two_sum(numbers, target):\n    seen = {}\n    for j, n in enumerate(numbers):\n        need = target - n\n        if need in seen:\n            return (seen[need], j)\n        seen[n] = j\n    return None\n\n\nprint(two_sum([2, 7, 11, 15], 9))\n`,
    hints: ['For each number, the partner you need is target - n.', 'Keep a dict of number → index for everything seen so far.'],
    tests: [
      { name: 'Basic', check: `assert tuple(two_sum([2, 7, 11, 15], 9)) == (0, 1)` },
      { name: 'Answer later in the list', check: `assert tuple(two_sum([3, 2, 4], 6)) == (1, 2)` },
      { name: 'Fast on 100k items', check: `import time\nnums = list(range(100000))\nt = time.perf_counter()\nassert tuple(two_sum(nums, 199997)) == (99998, 99999)\nassert time.perf_counter() - t < 1.5, "too slow — use a dict, not nested loops"` },
    ],
  },
  {
    slug: 'run-length-encoding',
    title: 'Run-length encoding',
    tier: 'apprentice',
    tags: ['strings'],
    prompt: 'Write encode(text) that compresses runs of repeated characters into the character followed by its count, and decode(encoded) that reverses it. Assume the input contains no digits.',
    examples: ['encode("aaabccdddd") → "a3b1c2d4"', 'decode("a3b1c2d4") → "aaabccdddd"'],
    starter: `def encode(text):\n    ...\n\n\ndef decode(encoded):\n    ...\n\n\nprint(encode("aaabccdddd"))\nprint(decode("a3b1c2d4"))\n`,
    solution: `def encode(text):\n    if not text:\n        return ""\n    parts = []\n    current, count = text[0], 1\n    for ch in text[1:]:\n        if ch == current:\n            count += 1\n        else:\n            parts.append(f"{current}{count}")\n            current, count = ch, 1\n    parts.append(f"{current}{count}")\n    return "".join(parts)\n\n\ndef decode(encoded):\n    result = []\n    i = 0\n    while i < len(encoded):\n        ch = encoded[i]\n        i += 1\n        digits = ""\n        while i < len(encoded) and encoded[i].isdigit():\n            digits += encoded[i]\n            i += 1\n        result.append(ch * int(digits))\n    return "".join(result)\n\n\nprint(encode("aaabccdddd"))\nprint(decode("a3b1c2d4"))\n`,
    hints: ['Track the current character and a count; flush when the character changes.', 'Counts can be more than one digit (e.g. "a12"), so read all consecutive digits when decoding.', 'itertools.groupby is a neat shortcut for encode.'],
    tests: [
      { name: 'encode', check: `assert encode("aaabccdddd") == "a3b1c2d4"` },
      { name: 'decode', check: `assert decode("a3b1c2d4") == "aaabccdddd"` },
      { name: 'Round trip with long runs', check: `s = "x" * 12 + "y" + "z" * 3\nassert decode(encode(s)) == s\nassert encode(s) == "x12y1z3"` },
      { name: 'Empty string', check: `assert encode("") == "" and decode("") == ""` },
    ],
  },
  {
    slug: 'matrix-transpose',
    title: 'Transpose a matrix',
    tier: 'apprentice',
    tags: ['lists', 'comprehensions'],
    prompt: 'Write transpose(matrix) that flips a list-of-lists over its diagonal: rows become columns. The matrix may be non-square.',
    examples: ['transpose([[1, 2, 3], [4, 5, 6]]) → [[1, 4], [2, 5], [3, 6]]'],
    starter: `def transpose(matrix):\n    ...\n\n\nprint(transpose([[1, 2, 3], [4, 5, 6]]))\n`,
    solution: `def transpose(matrix):\n    return [list(col) for col in zip(*matrix)]\n\n\nprint(transpose([[1, 2, 3], [4, 5, 6]]))\n`,
    hints: ['zip(*matrix) pairs up the first elements of every row, then the second, and so on.', 'Or use a nested comprehension over range(len(matrix[0])).'],
    tests: [
      { name: '2×3 becomes 3×2', check: `assert transpose([[1, 2, 3], [4, 5, 6]]) == [[1, 4], [2, 5], [3, 6]]` },
      { name: 'Square matrix', check: `assert transpose([[1, 2], [3, 4]]) == [[1, 3], [2, 4]]` },
      { name: 'Returns lists, not tuples', check: `assert all(isinstance(r, list) for r in transpose([[1, 2], [3, 4]]))` },
      { name: 'Transposing twice is identity', check: `m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nassert transpose(transpose(m)) == m` },
    ],
  },
  {
    slug: 'roman-numerals',
    title: 'Roman numerals',
    tier: 'apprentice',
    tags: ['numbers', 'strings'],
    prompt: 'Write to_roman(n) for 1 ≤ n ≤ 3999. Remember the subtractive forms: 4 is IV, 9 is IX, 40 is XL, 90 is XC, 400 is CD, 900 is CM.',
    examples: ['to_roman(1994) → "MCMXCIV"', 'to_roman(2026) → "MMXXVI"'],
    starter: `def to_roman(n):\n    ...\n\n\nprint(to_roman(1994))\n`,
    solution: `def to_roman(n):\n    values = [(1000, "M"), (900, "CM"), (500, "D"), (400, "CD"), (100, "C"), (90, "XC"),\n              (50, "L"), (40, "XL"), (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")]\n    out = ""\n    for value, symbol in values:\n        while n >= value:\n            out += symbol\n            n -= value\n    return out\n\n\nprint(to_roman(1994))\n`,
    hints: ['List the values from largest to smallest, including the subtractive pairs.', 'Greedy works: repeatedly subtract the largest value that fits.'],
    tests: [
      { name: '1994 → MCMXCIV', check: `assert to_roman(1994) == "MCMXCIV"` },
      { name: 'Small numbers', check: `assert to_roman(1) == "I" and to_roman(4) == "IV" and to_roman(9) == "IX"` },
      { name: '3999 → MMMCMXCIX', check: `assert to_roman(3999) == "MMMCMXCIX"` },
      { name: '2026 → MMXXVI', check: `assert to_roman(2026) == "MMXXVI"` },
    ],
  },
  {
    slug: 'binary-search',
    title: 'Binary search',
    tier: 'apprentice',
    tags: ['algorithms'],
    prompt: 'Write binary_search(sorted_list, target) that returns the index of target, or -1 if absent. Halve the search range each step; do not scan linearly.',
    examples: ['binary_search([1, 3, 5, 7, 9], 7) → 3'],
    starter: `def binary_search(sorted_list, target):\n    lo, hi = 0, len(sorted_list) - 1\n    ...\n\n\nprint(binary_search([1, 3, 5, 7, 9], 7))\n`,
    solution: `def binary_search(sorted_list, target):\n    lo, hi = 0, len(sorted_list) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if sorted_list[mid] == target:\n            return mid\n        if sorted_list[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\n\nprint(binary_search([1, 3, 5, 7, 9], 7))\n`,
    hints: ['Look at the middle element. If it is too small, search the right half; too big, the left half.', 'Loop while lo <= hi.'],
    tests: [
      { name: 'Finds 7 at index 3', check: `assert binary_search([1, 3, 5, 7, 9], 7) == 3` },
      { name: 'Missing returns -1', check: `assert binary_search([1, 3, 5, 7, 9], 4) == -1` },
      { name: 'Ends of the list', check: `assert binary_search([1, 3, 5], 1) == 0 and binary_search([1, 3, 5], 5) == 2` },
      { name: 'Logarithmic on a million items', check: `import time\nbig = list(range(0, 2000000, 2))\nt = time.perf_counter()\nfor _ in range(200):\n    assert binary_search(big, 1999998) == 999999\n    assert binary_search(big, 1) == -1\nassert time.perf_counter() - t < 1, "too slow — halve the range each iteration"` },
      { name: 'No .index() or "in" scanning', check: `assert ".index(" not in _src` },
    ],
  },
  {
    slug: 'balanced-brackets',
    title: 'Balanced brackets',
    tier: 'apprentice',
    tags: ['stacks', 'strings'],
    prompt: 'Write is_balanced(s) that returns True if every opening bracket ( [ { is closed by the matching type in the correct order. Ignore any other characters.',
    examples: ['is_balanced("{[()]}") → True', 'is_balanced("([)]") → False'],
    starter: `def is_balanced(s):\n    ...\n\n\nprint(is_balanced("{[()]}"), is_balanced("([)]"))\n`,
    solution: `def is_balanced(s):\n    pairs = {")": "(", "]": "[", "}": "{"}\n    stack = []\n    for ch in s:\n        if ch in "([{":\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack\n\n\nprint(is_balanced("{[()]}"), is_balanced("([)]"))\n`,
    hints: ['Use a list as a stack: push openers, pop on closers.', 'A closer must match the most recent opener; at the end the stack must be empty.'],
    tests: [
      { name: 'Nested', check: `assert is_balanced("{[()]}") is True` },
      { name: 'Wrong order', check: `assert is_balanced("([)]") is False` },
      { name: 'Unclosed and unopened', check: `assert is_balanced("((") is False and is_balanced(")") is False` },
      { name: 'Ignores other characters', check: `assert is_balanced("def f(x): return [x, {1: (2, 3)}]") is True` },
    ],
  },
  {
    slug: 'flatten',
    title: 'Flatten anything',
    tier: 'apprentice',
    tags: ['recursion', 'lists'],
    prompt: 'Write flatten(nested) that turns arbitrarily nested lists into one flat list, preserving order. Non-list items are kept as they are.',
    examples: ['flatten([1, [2, [3, [4]], 5]]) → [1, 2, 3, 4, 5]'],
    starter: `def flatten(nested):\n    ...\n\n\nprint(flatten([1, [2, [3, [4]], 5]]))\n`,
    solution: `def flatten(nested):\n    result = []\n    for item in nested:\n        if isinstance(item, list):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result\n\n\nprint(flatten([1, [2, [3, [4]], 5]]))\n`,
    hints: ['If an item is a list, flatten it recursively and extend the result.', 'Otherwise append the item itself.'],
    tests: [
      { name: 'Deeply nested', check: `assert flatten([1, [2, [3, [4]], 5]]) == [1, 2, 3, 4, 5]` },
      { name: 'Already flat', check: `assert flatten([1, 2, 3]) == [1, 2, 3]` },
      { name: 'Strings stay whole', check: `assert flatten([["ab", ["cd"]], "ef"]) == ["ab", "cd", "ef"]` },
      { name: 'Empty lists vanish', check: `assert flatten([[], [[]], [1, []]]) == [1]` },
    ],
  },

  // ───────────────────────────── Journeyman ─────────────────────────────
  {
    slug: 'group-anagrams',
    title: 'Group anagrams',
    tier: 'journeyman',
    tags: ['dicts', 'sorting'],
    prompt: 'Write group_anagrams(words) that groups words which are anagrams of each other. Return a list of groups (each a list, in original order), with the groups ordered by their first appearance.',
    examples: ['group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]) → [["eat", "tea", "ate"], ["tan", "nat"], ["bat"]]'],
    starter: `def group_anagrams(words):\n    ...\n\n\nprint(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))\n`,
    solution: `def group_anagrams(words):\n    groups = {}\n    for word in words:\n        key = "".join(sorted(word))\n        groups.setdefault(key, []).append(word)\n    return list(groups.values())\n\n\nprint(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))\n`,
    hints: ['The sorted letters of a word make a perfect dictionary key.', 'dict.setdefault(key, []) returns the existing list or creates one.', 'Dicts keep insertion order, so groups.values() is already in first-appearance order.'],
    tests: [
      { name: 'Classic example', check: `assert group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]) == [["eat", "tea", "ate"], ["tan", "nat"], ["bat"]]` },
      { name: 'No anagrams', check: `assert group_anagrams(["a", "b"]) == [["a"], ["b"]]` },
      { name: 'Empty input', check: `assert group_anagrams([]) == []` },
    ],
  },
  {
    slug: 'merge-intervals',
    title: 'Merge intervals',
    tier: 'journeyman',
    tags: ['sorting', 'algorithms'],
    prompt: 'Write merge_intervals(intervals), where each interval is a [start, end] list. Merge every pair that overlaps or touches and return the result sorted by start.',
    examples: ['merge_intervals([[1, 3], [2, 6], [8, 10], [15, 18]]) → [[1, 6], [8, 10], [15, 18]]', 'merge_intervals([[1, 4], [4, 5]]) → [[1, 5]]'],
    starter: `def merge_intervals(intervals):\n    ...\n\n\nprint(merge_intervals([[1, 3], [2, 6], [8, 10], [15, 18]]))\n`,
    solution: `def merge_intervals(intervals):\n    merged = []\n    for start, end in sorted(intervals):\n        if merged and start <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], end)\n        else:\n            merged.append([start, end])\n    return merged\n\n\nprint(merge_intervals([[1, 3], [2, 6], [8, 10], [15, 18]]))\n`,
    hints: ['Sort by start first.', 'If the next interval starts before (or at) the end of the last merged one, extend that end.'],
    tests: [
      { name: 'Overlapping', check: `assert merge_intervals([[1, 3], [2, 6], [8, 10], [15, 18]]) == [[1, 6], [8, 10], [15, 18]]` },
      { name: 'Touching', check: `assert merge_intervals([[1, 4], [4, 5]]) == [[1, 5]]` },
      { name: 'Unsorted input', check: `assert merge_intervals([[5, 7], [1, 2], [2, 4]]) == [[1, 4], [5, 7]]` },
      { name: 'Contained interval', check: `assert merge_intervals([[1, 10], [2, 3]]) == [[1, 10]]` },
    ],
  },
  {
    slug: 'lru-cache-class',
    title: 'Build an LRU cache',
    tier: 'journeyman',
    tags: ['classes', 'data structures'],
    prompt: 'Implement LRUCache(capacity) with get(key) and put(key, value). get returns the value or -1 if missing, and marks the key as recently used. put inserts or updates; when the cache is over capacity, evict the least recently used key. Python dicts remember insertion order, which is all you need.',
    starter: `class LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.data = {}\n\n    def get(self, key):\n        ...\n\n    def put(self, key, value):\n        ...\n\n\ncache = LRUCache(2)\ncache.put("a", 1)\ncache.put("b", 2)\nprint(cache.get("a"))   # 1, and "a" is now most recent\ncache.put("c", 3)       # evicts "b"\nprint(cache.get("b"))   # -1\n`,
    solution: `class LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.data = {}\n\n    def get(self, key):\n        if key not in self.data:\n            return -1\n        value = self.data.pop(key)\n        self.data[key] = value\n        return value\n\n    def put(self, key, value):\n        if key in self.data:\n            self.data.pop(key)\n        self.data[key] = value\n        if len(self.data) > self.capacity:\n            oldest = next(iter(self.data))\n            del self.data[oldest]\n\n\ncache = LRUCache(2)\ncache.put("a", 1)\ncache.put("b", 2)\nprint(cache.get("a"))   # 1, and "a" is now most recent\ncache.put("c", 3)       # evicts "b"\nprint(cache.get("b"))   # -1\n`,
    hints: ['To mark a key as recent, pop it and re-insert it — it moves to the end.', 'The least recently used key is the first one: next(iter(self.data)).'],
    tests: [
      { name: 'Basic get/put', check: `c = LRUCache(2)\nc.put("a", 1); c.put("b", 2)\nassert c.get("a") == 1\nassert c.get("z") == -1` },
      { name: 'Evicts least recently used', check: `c = LRUCache(2)\nc.put("a", 1); c.put("b", 2)\nc.get("a")\nc.put("c", 3)\nassert c.get("b") == -1 and c.get("a") == 1 and c.get("c") == 3` },
      { name: 'Updating a key refreshes it', check: `c = LRUCache(2)\nc.put("a", 1); c.put("b", 2)\nc.put("a", 10)\nc.put("c", 3)\nassert c.get("b") == -1 and c.get("a") == 10` },
      { name: 'Never exceeds capacity', check: `c = LRUCache(3)\nfor i in range(50):\n    c.put(i, i)\nassert len(c.data) == 3 and c.get(49) == 49 and c.get(0) == -1` },
    ],
  },
  {
    slug: 'spiral-matrix',
    title: 'Spiral order',
    tier: 'journeyman',
    tags: ['lists', 'algorithms'],
    prompt: 'Write spiral(matrix) that returns the elements of a 2-D list in clockwise spiral order, starting from the top-left corner.',
    examples: ['spiral([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) → [1, 2, 3, 6, 9, 8, 7, 4, 5]'],
    starter: `def spiral(matrix):\n    ...\n\n\nprint(spiral([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))\n`,
    solution: `def spiral(matrix):\n    result = []\n    rows = [list(r) for r in matrix]\n    while rows:\n        result.extend(rows.pop(0))\n        rows = [list(col) for col in zip(*rows)][::-1]\n    return result\n\n\nprint(spiral([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))\n`,
    hints: ['Take the top row, then rotate what remains counter-clockwise and repeat.', 'Rotating counter-clockwise is zip(*rows) reversed.'],
    tests: [
      { name: '3×3', check: `assert spiral([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) == [1, 2, 3, 6, 9, 8, 7, 4, 5]` },
      { name: '3×4', check: `assert spiral([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) == [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]` },
      { name: 'Single row and single column', check: `assert spiral([[1, 2, 3]]) == [1, 2, 3]\nassert spiral([[1], [2], [3]]) == [1, 2, 3]` },
      { name: 'Empty', check: `assert spiral([]) == []` },
    ],
  },
  {
    slug: 'memoize-decorator',
    title: 'Write memoize',
    tier: 'journeyman',
    tags: ['decorators', 'closures'],
    prompt: 'Write a decorator memoize that caches results by positional arguments, and exposes the number of cache hits as func.hits. Then use it on the slow recursive count_paths(rows, cols) so that count_paths(16, 16) returns instantly.',
    starter: `import functools\n\n\ndef memoize(func):\n    ...\n\n\n@memoize\ndef count_paths(rows, cols):\n    """Number of lattice paths from the top-left to bottom-right corner moving only right or down."""\n    if rows == 1 or cols == 1:\n        return 1\n    return count_paths(rows - 1, cols) + count_paths(rows, cols - 1)\n\n\nprint(count_paths(16, 16), count_paths.hits)\n`,
    solution: `import functools\n\n\ndef memoize(func):\n    cache = {}\n\n    @functools.wraps(func)\n    def wrapper(*args):\n        if args in cache:\n            wrapper.hits += 1\n            return cache[args]\n        result = func(*args)\n        cache[args] = result\n        return result\n\n    wrapper.hits = 0\n    return wrapper\n\n\n@memoize\ndef count_paths(rows, cols):\n    """Number of lattice paths from the top-left to bottom-right corner moving only right or down."""\n    if rows == 1 or cols == 1:\n        return 1\n    return count_paths(rows - 1, cols) + count_paths(rows, cols - 1)\n\n\nprint(count_paths(16, 16), count_paths.hits)\n`,
    hints: ['Keep a dict in the closure keyed by the args tuple.', 'Set wrapper.hits = 0 before returning the wrapper, and increment it on every cache hit.'],
    tests: [
      { name: 'count_paths(16, 16) is 155117520', check: `assert count_paths(16, 16) == 155117520` },
      { name: 'Records cache hits', check: `assert count_paths.hits > 0` },
      { name: 'Fast: count_paths(30, 30)', check: `import time\nt = time.perf_counter()\nassert count_paths(30, 30) == 30067266499541040\nassert time.perf_counter() - t < 1` },
      { name: 'Keeps the docstring (functools.wraps)', check: `assert count_paths.__doc__ and "lattice" in count_paths.__doc__` },
    ],
  },
  {
    slug: 'tokenizer-calculator',
    title: 'Expression calculator',
    tier: 'journeyman',
    tags: ['parsing', 'recursion'],
    prompt: 'Write evaluate(expr) that computes an arithmetic expression given as a string, supporting + - * /, parentheses, decimal numbers and the usual precedence. Do not use eval().',
    examples: ['evaluate("2 + 3 * 4") → 14', 'evaluate("(2 + 3) * 4") → 20', 'evaluate("10 / 4") → 2.5'],
    starter: `def evaluate(expr):\n    ...\n\n\nprint(evaluate("2 + 3 * 4"), evaluate("(2 + 3) * 4"))\n`,
    solution: `import re\n\n\ndef evaluate(expr):\n    tokens = re.findall(r"\\d+\\.?\\d*|[-+*/()]", expr)\n    pos = 0\n\n    def peek():\n        return tokens[pos] if pos < len(tokens) else None\n\n    def take():\n        nonlocal pos\n        tok = tokens[pos]\n        pos += 1\n        return tok\n\n    def factor():\n        tok = take()\n        if tok == "(":\n            value = expression()\n            take()  # ')'\n            return value\n        if tok == "-":\n            return -factor()\n        return float(tok)\n\n    def term():\n        value = factor()\n        while peek() in ("*", "/"):\n            if take() == "*":\n                value *= factor()\n            else:\n                value /= factor()\n        return value\n\n    def expression():\n        value = term()\n        while peek() in ("+", "-"):\n            if take() == "+":\n                value += term()\n            else:\n                value -= term()\n        return value\n\n    return expression()\n\n\nprint(evaluate("2 + 3 * 4"), evaluate("(2 + 3) * 4"))\n`,
    hints: ['Tokenise first: numbers and single-character operators.', 'Recursive descent: expression = term (+|- term)*, term = factor (*|/ factor)*, factor = number | ( expression ) | - factor.', 'A nonlocal position index shared by the helper functions keeps things simple.'],
    tests: [
      { name: 'Precedence', check: `assert evaluate("2 + 3 * 4") == 14` },
      { name: 'Parentheses', check: `assert evaluate("(2 + 3) * 4") == 20` },
      { name: 'Division and decimals', check: `import math\nassert math.isclose(evaluate("10 / 4"), 2.5)\nassert math.isclose(evaluate("1.5 * 2 + 0.25"), 3.25)` },
      { name: 'Nested and unary minus', check: `assert evaluate("((1 + 2) * (3 + 4)) - -1") == 22` },
      { name: 'No eval()', check: `assert "eval(" not in _src.replace("evaluate(", "")` },
    ],
  },
  {
    slug: 'inventory-report',
    title: 'Inventory report',
    tier: 'journeyman',
    tags: ['dataclasses', 'formatting'],
    prompt: 'Given a list of Item dataclasses, write report(items) that returns a multi-line string: one line per item as NAME padded to 12 chars, quantity right-aligned in 4, and total value (qty × price) right-aligned in 9 with two decimals; then a final line TOTAL followed by the grand total in the same 9-wide column. Sort items by name.',
    examples: ['bolt          40    10.00', 'washer       100     5.00', 'TOTAL               15.00'],
    starter: `from dataclasses import dataclass\n\n\n@dataclass\nclass Item:\n    name: str\n    qty: int\n    price: float\n\n\ndef report(items):\n    ...\n\n\nstock = [Item("washer", 100, 0.05), Item("bolt", 40, 0.25)]\nprint(report(stock))\n`,
    solution: `from dataclasses import dataclass\n\n\n@dataclass\nclass Item:\n    name: str\n    qty: int\n    price: float\n\n\ndef report(items):\n    lines = []\n    total = 0.0\n    for item in sorted(items, key=lambda i: i.name):\n        value = item.qty * item.price\n        total += value\n        lines.append(f"{item.name:<12}{item.qty:>4}{value:>9.2f}")\n    lines.append(f"{'TOTAL':<16}{total:>9.2f}")\n    return "\\n".join(lines)\n\n\nstock = [Item("washer", 100, 0.05), Item("bolt", 40, 0.25)]\nprint(report(stock))\n`,
    hints: ['f"{name:<12}" pads left-aligned to 12; f"{n:>9.2f}" right-aligns a float to 9 with two decimals.', 'The TOTAL line has no quantity, so pad the label to 16 to line up the value column.'],
    tests: [
      { name: 'Rows are sorted and formatted', check: `out = report([Item("washer", 100, 0.05), Item("bolt", 40, 0.25)]).splitlines()\nassert out[0] == "bolt          40    10.00", repr(out[0])\nassert out[1] == "washer       100     5.00", repr(out[1])` },
      { name: 'Total line', check: `out = report([Item("washer", 100, 0.05), Item("bolt", 40, 0.25)]).splitlines()\nassert out[-1] == "TOTAL               15.00", repr(out[-1])` },
      { name: 'Empty inventory', check: `assert report([]) == "TOTAL                0.00"` },
    ],
  },
]

export function getChallenge(slug: string) {
  return challenges.find(c => c.slug === slug)
}
